"""Rename metadata column to meta_info

Revision ID: fb392977c884
Revises: f42c08c5d882
Create Date: 2025-01-03 17:15:08.561002

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import JSONB
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'fb392977c884'
down_revision: Union[str, None] = 'f42c08c5d882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute('DROP INDEX IF EXISTS ix_student_metadata_gin;')
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("CREATE INDEX idx_gin_info ON student USING GIN ((meta_info::text) gin_trgm_ops);")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX idx_gin_info;")
    # ### end Alembic commands ###